-- ============================================================
-- Mise — make RLS actually enforce  (Sprint 7 Part 30, ADR 0030)
-- ============================================================
-- RUN THIS BY HAND, AS THE TABLE OWNER (neondb_owner), VIA DIRECT_URL.
-- It is NOT a Prisma migration and must not be moved into prisma/migrations/
-- (Sprint 0 convention, and it manages a ROLE, which migrations must not).
--
-- WHAT IS WRONG TODAY, MEASURED RATHER THAN ASSUMED:
--
--     connecting role : neondb_owner — rolbypassrls TRUE, owns the tables TRUE
--     54 tables · RLS enabled 47 · RLS FORCED 0 · policies 47
--
-- Row-level security has been ENABLED since Sprint 0 and has never filtered a
-- single row, because the application connects as a role that bypasses it
-- twice over. ADR 0004 Consequence 3 recorded this in Sprint 1 and deferred
-- the fix to Sprint 7 by name.
--
-- WHY `FORCE ROW LEVEL SECURITY` IS NOT THE FIX ON ITS OWN. FORCE removes the
-- OWNER's bypass. It does nothing about the `BYPASSRLS` ATTRIBUTE, which
-- neondb_owner also carries (Neon grants it neon_superuser). Section 3 below
-- would be forty-seven no-ops without section 1.
--
-- ORDER MATTERS. Sections 1 and 2 are safe to run at any time: they create a
-- role nothing is using yet. Section 3 and 4 are the switch, and the moment
-- DATABASE_URL points at mise_app the policies start filtering for real.
--
-- 🛑 BEFORE RUNNING SECTION 3-4, THE APPLICATION CODE MUST ALREADY BE ON THE
--    Part 30 L1+ changes. Running them against today's code will:
--      * make it impossible to create a new shop (createTenant writes seven
--        rows before the tenant exists, and the `tenant` policy's USING acts
--        as WITH CHECK)
--      * break login (require-tenant.ts discovers the tenant by userId, with
--        no tenant context to discover it in)
--    Sections 1-2 first, then the code, then 3-4.
-- ============================================================


-- ============================================================
-- 1. The application role
-- ============================================================
-- Not the owner of anything, and no BYPASSRLS. That combination is what makes
-- the forty-seven existing policies apply at all — it is the whole fix.
--
-- ⚠️ REPLACE THE PASSWORD BELOW BEFORE RUNNING, AND DO NOT COMMIT THE FILLED
--    VERSION. Generate one that is long and random; it goes into DATABASE_URL
--    and nowhere else.

CREATE ROLE mise_app WITH LOGIN PASSWORD 'REPLACE_ME_BEFORE_RUNNING';

-- Neon puts every role in the `neon_superuser` group by default in some
-- setups; that group carries BYPASSRLS and would silently undo this whole
-- file. Revoking is harmless if it was never granted.
REVOKE neon_superuser FROM mise_app;

-- ⚠️ THERE IS NO `ALTER ROLE ... NOSUPERUSER` HERE, AND THAT IS DELIBERATE.
-- The obvious belt-and-braces line
--
--     ALTER ROLE mise_app NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE;
--
-- CANNOT RUN on Neon: neondb_owner is not a superuser, and Postgres answers
-- "Only roles with the SUPERUSER attribute may change the SUPERUSER attribute".
-- In a pasted batch that error stops every statement after it — which is
-- exactly what happened the first time this file was run, leaving a role that
-- could log in and had no grants at all.
--
-- It is also unnecessary: a role created by SQL gets NOSUPERUSER and
-- NOBYPASSRLS by default. Verify rather than assert (section 5).


-- ============================================================
-- 2. What the application role may do
-- ============================================================
-- DML only. No DDL: migrations keep running as the owner through DIRECT_URL,
-- so the role the internet can reach cannot alter a table.

GRANT USAGE ON SCHEMA public TO mise_app;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA public TO mise_app;

-- Prisma's own bookkeeping is the owner's business. The app never reads it,
-- and a role that can rewrite migration history is a role that can lie about
-- what shape the database is in.
REVOKE ALL ON TABLE "_prisma_migrations" FROM mise_app;

-- THE LINE THAT MATTERS SIX MONTHS FROM NOW. Without it, the first table a
-- future Part adds is invisible to the application — and the failure arrives
-- as "permission denied for table staff_roster" on a screen, long after the
-- migration that looked fine.
ALTER DEFAULT PRIVILEGES FOR ROLE neondb_owner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mise_app;

-- No sequence grants: every id in this schema is a uuid or a cuid generated by
-- the application or by gen_random_uuid(), and nothing uses a serial. If that
-- ever changes, sequences need USAGE here too.


-- ============================================================
-- 3. Make the owner subject to its own policies
-- ============================================================
-- Redundant while the app connects as mise_app, which is not the owner. It is
-- here for the day ownership moves, or a role is granted more than intended:
-- without it, that day is silent, and silence is precisely how this went
-- unnoticed for twenty-nine Parts.

ALTER TABLE "branch" FORCE ROW LEVEL SECURITY;
ALTER TABLE "category" FORCE ROW LEVEL SECURITY;
ALTER TABLE "department" FORCE ROW LEVEL SECURITY;
ALTER TABLE "expense" FORCE ROW LEVEL SECURITY;
ALTER TABLE "expense_item" FORCE ROW LEVEL SECURITY;
ALTER TABLE "goods_receipt" FORCE ROW LEVEL SECURITY;
ALTER TABLE "goods_receipt_item" FORCE ROW LEVEL SECURITY;
ALTER TABLE "goods_receipt_item_allocation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "menu" FORCE ROW LEVEL SECURITY;
ALTER TABLE "menu_alias" FORCE ROW LEVEL SECURITY;
ALTER TABLE "menu_category" FORCE ROW LEVEL SECURITY;
ALTER TABLE "menu_merge" FORCE ROW LEVEL SECURITY;
ALTER TABLE "par_level" FORCE ROW LEVEL SECURITY;
ALTER TABLE "pos_integration" FORCE ROW LEVEL SECURITY;
ALTER TABLE "product" FORCE ROW LEVEL SECURITY;
ALTER TABLE "product_unit" FORCE ROW LEVEL SECURITY;
ALTER TABLE "purchase_order" FORCE ROW LEVEL SECURITY;
ALTER TABLE "purchase_order_item" FORCE ROW LEVEL SECURITY;
ALTER TABLE "purchase_order_item_allocation" FORCE ROW LEVEL SECURITY;
ALTER TABLE "recipe" FORCE ROW LEVEL SECURITY;
ALTER TABLE "recipe_branch" FORCE ROW LEVEL SECURITY;
ALTER TABLE "recipe_ingredient" FORCE ROW LEVEL SECURITY;
ALTER TABLE "recurring_expense" FORCE ROW LEVEL SECURITY;
ALTER TABLE "sales_consumption_item" FORCE ROW LEVEL SECURITY;
ALTER TABLE "sales_consumption_run" FORCE ROW LEVEL SECURITY;
ALTER TABLE "sales_day" FORCE ROW LEVEL SECURITY;
ALTER TABLE "sales_import_batch" FORCE ROW LEVEL SECURITY;
ALTER TABLE "sales_import_profile" FORCE ROW LEVEL SECURITY;
ALTER TABLE "sales_line" FORCE ROW LEVEL SECURITY;
ALTER TABLE "staff_meal" FORCE ROW LEVEL SECURITY;
ALTER TABLE "staff_meal_item" FORCE ROW LEVEL SECURITY;
ALTER TABLE "staff_member" FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_adjustment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_cost_declaration" FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_count" FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_count_entry" FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_count_item" FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_movement" FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_transfer" FORCE ROW LEVEL SECURITY;
ALTER TABLE "stock_transfer_item" FORCE ROW LEVEL SECURITY;
ALTER TABLE "supplier" FORCE ROW LEVEL SECURITY;
ALTER TABLE "supplier_product_mapping" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant" FORCE ROW LEVEL SECURITY;
ALTER TABLE "tenant_membership" FORCE ROW LEVEL SECURITY;
ALTER TABLE "user_branch_access" FORCE ROW LEVEL SECURITY;
ALTER TABLE "user_department_assignment" FORCE ROW LEVEL SECURITY;
ALTER TABLE "waste_log" FORCE ROW LEVEL SECURITY;

-- ============================================================
-- 4. Policies that refuse to be polite about a missing context
-- ============================================================
-- Every policy reads `current_setting('app.current_tenant_id', true)`, and
-- that `true` means "return NULL instead of raising when it is unset". NULL
-- makes the comparison false, so a query with no tenant context returns ZERO
-- ROWS, silently — the shop phones to say the data has disappeared, and the
-- investigation starts at the data.
--
-- Dropping the flag turns that into an error, in development, where it is a
-- bug. This is rule A8 one level up: ADR 0029 refused to let "you may not see
-- this" render as ฿0, because absence and refusal are different facts.
--
-- ALTER rather than DROP + CREATE: a dropped policy is a table with no policy,
-- and if this file fails halfway through, that table is wide open.
--
-- All forty-seven are `FOR ALL` with no separate WITH CHECK, so Postgres uses
-- the USING expression for inserts and updates too — which is why section 4
-- alone governs both what can be read and what can be written.

ALTER POLICY tenant_isolation ON "branch" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "category" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "department" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "expense" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "expense_item" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "goods_receipt" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "goods_receipt_item" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "goods_receipt_item_allocation" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "menu" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "menu_alias" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "menu_category" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "menu_merge" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "par_level" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "pos_integration" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "product" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "product_unit" USING ((EXISTS ( SELECT 1
   FROM product p
  WHERE ((p.id = product_unit.product_id) AND (p.tenant_id = (current_setting('app.current_tenant_id'::text))::uuid)))));
ALTER POLICY tenant_isolation ON "purchase_order" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "purchase_order_item" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "purchase_order_item_allocation" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "recipe" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "recipe_branch" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "recipe_ingredient" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "recurring_expense" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "sales_consumption_item" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "sales_consumption_run" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "sales_day" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "sales_import_batch" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "sales_import_profile" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "sales_line" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "staff_meal" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "staff_meal_item" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "staff_member" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "stock_adjustment" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "stock_cost_declaration" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "stock_count" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "stock_count_entry" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "stock_count_item" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "stock_movement" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "stock_transfer" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "stock_transfer_item" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "supplier" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "supplier_product_mapping" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "tenant" USING ((id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "tenant_membership" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));
ALTER POLICY tenant_isolation ON "user_branch_access" USING ((EXISTS ( SELECT 1
   FROM tenant_membership tm
  WHERE ((tm.id = user_branch_access.tenant_membership_id) AND (tm.tenant_id = (current_setting('app.current_tenant_id'::text))::uuid)))));
ALTER POLICY tenant_isolation ON "user_department_assignment" USING ((EXISTS ( SELECT 1
   FROM tenant_membership tm
  WHERE ((tm.id = user_department_assignment.tenant_membership_id) AND (tm.tenant_id = (current_setting('app.current_tenant_id'::text))::uuid)))));
ALTER POLICY tenant_isolation ON "waste_log" USING ((tenant_id = (current_setting('app.current_tenant_id'::text))::uuid));

-- ============================================================
-- 5. Verify — run these and read them, do not assume
-- ============================================================
-- Expected after the whole file: forced 47, polite 0, and mise_app holding
-- neither superuser nor bypassrls.

-- select count(*) filter (where relrowsecurity) as enabled,
--        count(*) filter (where relforcerowsecurity) as forced
-- from pg_class c join pg_namespace n on n.oid = c.relnamespace
-- where n.nspname = 'public' and c.relkind = 'r';

-- select count(*) as still_polite from pg_policies
-- where schemaname = 'public' and qual like '%, true)%';

-- select rolname, rolsuper, rolbypassrls, rolcanlogin
-- from pg_roles where rolname = 'mise_app';

-- The one that actually proves it, run while connected AS mise_app:
--   select count(*) from branch;            -- expect: ERROR, not 0 rows
--   begin;
--     select set_config('app.current_tenant_id', '<some tenant uuid>', true);
--     select count(*) from branch;          -- expect: only that tenant's
--   rollback;
